bundler_args: --without production
before_script: bundle exec rails db:create db:migrate
cache: bundler
language: ruby
rvm:
  - 2.4.0
sript:
  - bundle exec rspec
sudo: false
dist: xenial
branch:
  only:
    - master
    - homolog
deploy:
  provider: heroku
  api_key:
    secure: "d5573795-53f2-49f9-8180-ac98f4af24f0"
  app:
    homolog: cadernos-api
  run:
    - "rake db:migrate"
addons:
    code_climate:
        repo_token: c277e3c368b533d9674e2e08ddc7db4e155899532abf9e11fdd0531e9d848be1

